### ISSUE TITLE
Formula interpretation

### ISSUE THREAD

**Issue by jgmatos** [talkdesk-challenges/challenges#30]
Hi,

I have a few questions regarding the interpretation of the billing formula. I apologize if I missed anything obvious.

Regarding the billing formula: talkdesk_number_cost + external_number_cost + profit_margin

1) the prices specified in the CSV file correspond to the profit margin, correct?

2) talkdesk_number_cost should be set to 1c, except for UK/US toll-free numbers. Do you have a list of these exceptions? (e.g. 0800 is a UK toll-free number that is not provided in the CSV file)

3) The sole purpose of the forwarded_phone_number parameter is to know whether (or not) the user answered the call using the webrowser?

4) It is mentioned that the profit margin may decrease for some customers. What rules should be applied here?

Maybe it becomes easier to explain/understand with a few examples.

Thanks in advance.

**Comment by ivoanjo** [comment]
Hey @jgmatos!

In order:

1.  The prices specified in the `csv` are twilio's prices
2.  There are several sources online for the prefixes for uk/us toll-free numbers :)
3.  The `forwarded_phone_number` allows you to distinguish if a call was forwarded to an external phone number or not (which you'll need when calculating the price)
4.  An example is given in the problem statement: *"for example, reduce the margin if they use a lot of minutes per month"*, and while I recommend you don't go too overboard here, it's expected that in the future more would be added.

**Comment by jgmatos** [comment]
Hi @ivoanjo,

thank you for the quick reply, I think I got most of it now :) I'm just a bit insecure regarding question 4: i) how much is the standard profit margin?; how many minutes per month are required to get a discount on the profit margin?; iii) how much is the discount?

Should I choose some default values and enable setting custom values? 

Thanks for the patience

**Comment by jgmatos** [comment]
Hi @ivoanjo ,

sorry for the repetition, but just to be 100% sure: since there are (potentially) three phone numbers in the call_billing command and only two of them are used in the formula, the customer_phone_number is the one that is NOT used in the formula, correct? 

Again, thanks for the patience

**Comment by ivoanjo** [comment]
Hello again,

* The profit margin is in the problem description. I suggest you re-read it carefully :)
* The discount is given as an example of the flexibility we expect the system to have, but the idea is that we haven't yet decided on the values.
* You are correct, the `customer_phone_number` is not used to bill. Although in some phone systems, if you call from a 1-800 to a 1-800 there are interesting billing implications, but you may disregard that here.
