### ISSUE TITLE
Challenge Chosen

### ISSUE THREAD

**Issue by jccguimaraes** [talkdesk-challenges/challenges#43]
I choose this challenge **(Frontend - Browser Telephone)**

Can you give me more intel on how to start and setup trilio and stuff?

Thanks

**Comment by joao-quiterio** [comment]
Hey @jccguimaraes, are you in contact with one of our recruiters?
If yes, please create the issues in the repository that our awesome People Team created for you.
If no, let me start by introducing you to @heliodavidcosta and @franciscogrsilva
